In [19]:
import numpy as np
import pandas as pd

In [20]:
# Define column names based on the header in the SRL file
column_names = [
    "Source_id", "Isl_id", "RA", "E_RA", "DEC", "E_DEC", "Total_flux", "E_Total_flux",
    "Peak_flux", "E_Peak_flux", "RA_max", "E_RA_max", "DEC_max", "E_DEC_max", "Maj", 
    "E_Maj", "Min", "E_Min", "PA", "E_PA", "Maj_img_plane", "E_Maj_img_plane", 
    "Min_img_plane", "E_Min_img_plane", "PA_img_plane", "E_PA_img_plane", "DC_Maj", 
    "E_DC_Maj", "DC_Min", "E_DC_Min", "DC_PA", "E_DC_PA", "DC_Maj_img_plane", 
    "E_DC_Maj_img_plane", "DC_Min_img_plane", "E_DC_Min_img_plane", "DC_PA_img_plane", 
    "E_DC_PA_img_plane", "Isl_Total_flux", "E_Isl_Total_flux", "Isl_rms", "Isl_mean", 
    "Resid_Isl_rms", "Resid_Isl_mean", "S_Code"
]

In [33]:
# Assuming 'file.srl' is the SRL file
srl_file_path_1 = '../server/noise_detecting/03:32:04.530001_+31.05.04.00000-mosaic-fieldALL-StokesI-2.5arc-5000-1e-4-spwALL-pb0.06-cyclenit500.image.pybdsf.srl'
srl_file_path_2 = '../server/noise_detecting/03:36:00.000000_+30.30.00.00001-mosaic-fieldALL-StokesI-2.5arc-5000-1e-4-spwALL-pb0.06-cyclenit500.image.pybdsf.srl'
srl_file_path_3 = '../server/noise_detecting/03:25:30.000000_+29.29.59.99999-mosaic-fieldALL-StokesI-2.5arc-5000-1e-4-spwALL-pb0.06-cyclenit500.image.pybdsf.srl'

In [34]:
# Read the SRL file into a DataFrame
df_1 = pd.read_csv(srl_file_path_1, delim_whitespace=True, comment='#', names=column_names)
df_2 = pd.read_csv(srl_file_path_2, delim_whitespace=True, comment='#', names=column_names)
df_3 = pd.read_csv(srl_file_path_3, delim_whitespace=True, comment='#', names=column_names)

In [28]:
df_1

,Source_id,Isl_id,RA,E_RA,DEC,E_DEC,Total_flux,E_Total_flux,Peak_flux,E_Peak_flux,...,E_DC_Min_img_plane,DC_PA_img_plane,E_DC_PA_img_plane,Isl_Total_flux,E_Isl_Total_flux,Isl_rms,Isl_mean,Resid_Isl_rms,Resid_Isl_mean,S_Code
0,0,0,54.310933,0.000666,31.250419,0.000414,0.001827,0.000236,0.001143,0.000098,...,0.000905,102.082591,13.432194,0.001216,0.000077,0.000092,-0.000023,0.000038,-0.000023,S
1,1,1,54.171368,0.001042,31.298449,0.000766,0.000560,0.000178,0.000544,0.000100,...,0.001743,0.000000,45.318135,0.000331,0.000064,0.000100,-0.000016,0.000004,-0.000016,S
2,2,2,54.161745,0.000880,31.107435,0.001511,0.000629,0.000206,0.000461,0.000095,...,0.002031,0.000000,32.557066,0.000341,0.000059,0.000091,-0.000008,0.000006,-0.000008,S
3,3,3,54.151808,0.000727,31.277171,0.000738,0.000688,0.000176,0.000666,0.000099,...,0.001469,0.000000,45.959200,0.000451,0.000069,0.000099,-0.000015,0.000007,-0.000015,S
4,4,4,54.019647,0.001254,31.361442,0.001095,0.000814,0.000269,0.000609,0.000127,...,0.002255,135.068708,49.688863,0.000437,0.000078,0.000121,-0.000007,0.000012,-0.000006,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,441,413,51.912929,0.000161,31.461384,0.000115,0.003200,0.000140,0.002749,0.000072,...,0.000264,86.099749,5.450461,0.002959,0.000087,0.000071,-0.000025,0.000032,-0.000024,S
442,442,414,51.898324,0.000684,31.508254,0.000559,0.000803,0.000145,0.000646,0.000072,...,0.001084,128.315343,19.128786,0.000591,0.000062,0.000069,-0.000022,0.000006,-0.000022,S
443,443,415,51.877335,0.001268,31.177902,0.000827,0.000599,0.000176,0.000461,0.000084,...,0.001725,107.600899,26.758280,0.000352,0.000059,0.000081,-0.000018,0.000006,-0.000018,S
444,444,416,51.845183,0.000108,31.167982,0.000096,0.006900,0.000186,0.005034,0.000086,...,0.000171,135.382715,2.148761,0.006926,0.000120,0.000082,-0.000017,0.000079,0.000002,S
445,445,417,51.806778,0.000353,30.680137,0.000289,0.001289,0.000148,0.001289,0.000085,...,0.000634,0.000000,17.852752,0.000208,0.000048,0.000086,-0.000025,0.000193,-0.000292,S

In [29]:
df_2

,Source_id,Isl_id,RA,E_RA,DEC,E_DEC,Total_flux,E_Total_flux,Peak_flux,E_Peak_flux,...,E_DC_Min_img_plane,DC_PA_img_plane,E_DC_PA_img_plane,Isl_Total_flux,E_Isl_Total_flux,Isl_rms,Isl_mean,Resid_Isl_rms,Resid_Isl_mean,S_Code
0,0,0,55.257375,0.000737,30.649781,0.000623,0.000824,0.000172,0.000717,0.000090,...,0.001297,144.589777,30.283616,0.000600,0.000069,0.000088,-0.000012,0.000011,-1.219552e-05,S
1,1,2,55.145919,0.001040,30.230918,0.001258,0.000539,0.000166,0.000391,0.000077,...,0.002327,23.777230,58.585324,0.000302,0.000050,0.000073,-0.000008,0.000005,-8.118128e-06,S
2,2,3,55.094928,0.000954,30.924116,0.000815,0.000652,0.000185,0.000631,0.000103,...,0.001440,140.383375,26.393024,0.000387,0.000068,0.000104,-0.000025,0.000007,-2.467907e-05,S
3,3,4,55.058451,0.000392,29.867310,0.000322,0.001039,0.000121,0.000976,0.000067,...,0.000674,143.033288,16.200363,0.000739,0.000049,0.000066,-0.000011,0.000014,-1.101083e-05,S
4,4,5,55.055604,0.001584,30.002658,0.001654,0.000742,0.000201,0.000383,0.000071,...,0.001750,139.696789,17.354279,0.000410,0.000072,0.000070,-0.000011,0.000020,-1.118121e-05,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,338,314,52.929250,0.001246,30.704933,0.000972,0.001123,0.000276,0.000693,0.000113,...,0.001757,125.162076,22.193482,0.000736,0.000088,0.000107,-0.000010,0.000011,-9.542273e-06,S
339,339,315,52.917637,0.000258,30.675695,0.000181,0.003439,0.000223,0.002878,0.000114,...,0.000400,95.283968,7.153863,0.003240,0.000113,0.000110,-0.000012,0.000055,-6.230061e-06,S
340,340,316,52.909981,0.001417,30.430264,0.000859,0.000693,0.000232,0.000634,0.000123,...,0.001538,0.000000,21.506604,0.000363,0.000079,0.000125,-0.000026,0.000005,-2.624036e-05,S
341,341,317,52.842908,0.001176,30.228746,0.000587,0.001476,0.000307,0.000966,0.000130,...,0.001332,92.835602,15.908566,0.001114,0.000119,0.000125,-0.000019,0.000039,-1.747109e-05,S
342,342,318,52.827314,0.000049,30.791437,0.000081,0.010188,0.000342,0.008792,0.000099,...,0.000096,0.000000,1.428398,0.009932,0.000160,0.000099,-0.000008,0.000056,-8.531297e-07,M

In [35]:
df_3

,Source_id,Isl_id,RA,E_RA,DEC,E_DEC,Total_flux,E_Total_flux,Peak_flux,E_Peak_flux,...,E_DC_Min_img_plane,DC_PA_img_plane,E_DC_PA_img_plane,Isl_Total_flux,E_Isl_Total_flux,Isl_rms,Isl_mean,Resid_Isl_rms,Resid_Isl_mean,S_Code
0,0,1,52.563710,0.000509,29.535957,0.000444,0.002987,0.000414,0.002460,0.000208,...,0.000860,139.933788,17.188498,0.002694,0.000254,0.000202,-0.000028,0.000138,-7.139223e-06,S
1,1,2,52.475851,0.001275,29.681067,0.000964,0.002027,0.000490,0.001261,0.000200,...,0.001565,51.664263,19.040223,0.001401,0.000187,0.000192,-0.000023,0.000048,-2.196451e-05,S
2,2,3,52.460367,0.000316,29.133319,0.000243,0.003947,0.000330,0.003285,0.000167,...,0.000535,108.688823,12.432763,0.003702,0.000168,0.000162,-0.000004,0.000055,-8.387203e-07,S
3,3,4,52.464779,0.000147,29.821086,0.000096,0.006239,0.000242,0.005623,0.000129,...,0.000224,0.000000,5.170141,0.005913,0.000143,0.000127,-0.000018,0.000097,-1.263495e-05,S
4,4,5,52.408785,0.000368,29.848280,0.000310,0.001484,0.000187,0.001594,0.000113,...,0.000687,0.000000,23.482546,0.001235,0.000098,0.000116,-0.000018,0.000015,-1.869457e-05,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,379,341,50.385600,0.000969,29.163267,0.000701,0.001016,0.000222,0.000781,0.000105,...,0.001240,123.192206,16.899860,0.000673,0.000078,0.000103,-0.000026,0.000012,-2.550498e-05,S
380,380,343,50.343143,0.000731,29.728826,0.000554,0.000881,0.000166,0.000709,0.000083,...,0.001280,76.254277,31.198432,0.000646,0.000069,0.000079,-0.000023,0.000006,-2.310159e-05,S
381,381,344,50.343242,0.000628,29.275546,0.000414,0.001336,0.000198,0.001053,0.000097,...,0.000943,92.796452,16.626968,0.001112,0.000088,0.000093,-0.000016,0.000014,-1.524244e-05,S
382,382,345,50.297553,0.000297,29.016885,0.000237,0.002094,0.000187,0.002016,0.000105,...,0.000496,133.473016,10.737834,0.002965,0.000196,0.000104,-0.000035,0.000126,2.276079e-04,S
383,383,346,50.242044,0.000116,29.229682,0.000327,0.004699,0.000266,0.003116,0.000093,...,0.000263,0.000000,3.101507,0.004384,0.000123,0.000093,-0.000016,0.000014,-1.600738e-05,M

In [36]:
print('Noise level of Mosaic1:')
np.mean(df_1['Resid_Isl_rms'])

Noise level of Mosaic1:

3.410737613365468e-05

In [37]:
print('Noise level of Mosaic2:')
np.mean(df_2['Resid_Isl_rms'])

Noise level of Mosaic2:

5.52051548188921e-05

In [39]:
print('Noise level of Mosaic4:')
np.mean(df_3['Resid_Isl_rms'])

Noise level of Mosaic4:

4.7038211956536536e-05